<a href="https://colab.research.google.com/github/tusharthe/Python-Programming-Assignments/blob/main/Python_Array_Manipulation_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [202]:
import numpy as np

## 1. Convert the given list into a numpy array and replace the odd elements with -2.
Lst =[[1,2,3],
 [4,5,6],
[7,8,9]]


In [203]:
lst =[[1,2,3],
 [4,5,6],
[7,8,9]]


In [204]:
list = np.array(lst);
list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [205]:
list[list % 2 != 0] = -2
display(list)

array([[-2,  2, -2],
       [ 4, -2,  6],
       [-2,  8, -2]])

## 2. In the numpy array given below print all the elements ranging from 8 to 15.
arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]


In [206]:
arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]
arr = np.array(arr)

In [207]:
for aarray in arr:
  if aarray >= 8 and aarray <= 15:
    print(aarray)

8
9
10
12


In [208]:
print(arr[(arr >= 8) & (arr <= 15)])

[ 8  9 10 12]


## Create a 3*3 narray that includes numbers from 1 to 9 and swap columns 1 and 2.

In [209]:
import numpy as np

array = np.array([[1,2,3],[4,5,6], [7,8,9]])
print("Original array:")
print(array)
print()

# Swap columns 1 and 2 (remembering that indexing starts at 0)
col1 = array[:, 0].copy() # Create a copy of the first column
array[:, 0] = array[:, 1]
array[:, 1] = col1

print("Array after swapping columns 1 and 2:")
print(array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping columns 1 and 2:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


## In the given numpy array replace the NaN values with the average of columns
arr = np.array([[1.3, 2.5, 3.6, np.nan],
 [2.6, 3.3, np.nan, 5.5],
 [2.1, 3.2, 5.4, 6.5]])


In [210]:
arr = np.array([[1.3, 2.5, 3.6, np.nan],
 [2.6, 3.3, np.nan, 5.5],
 [2.1, 3.2, 5.4, 6.5]])
arr

array([[1.3, 2.5, 3.6, nan],
       [2.6, 3.3, nan, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

In [211]:
np.isnan(arr)

array([[False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [212]:
col_means = np.nanmean(arr, axis=0)
# print(col_means)
for i in range(arr.shape[1]):
  arr[np.isnan(arr[:, i]), i] = col_means[i]

display(arr)

array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

## 5. For the numpy array given below perform the following operation:


1.   Convert the numpy array into a numpy matrix
2.   Sort the values in a matrix


arr = [[2,4,6],
[1,3,5]]

In [213]:
arr = [[2,4,6],
[1,3,5]]
arr

[[2, 4, 6], [1, 3, 5]]

In [214]:
array = np.array(arr)
display(array)

array([[2, 4, 6],
       [1, 3, 5]])

In [215]:
array2 = np.matrix(array)
array2

matrix([[2, 4, 6],
        [1, 3, 5]])

In [216]:
sorted_array = np.sort(np.asarray(array2).flatten())
display(sorted_array)

array([1, 2, 3, 4, 5, 6])